import type { Metadata, Viewport } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CartDrawer from "@/components/CartDrawer";
import WhatsAppFloatingButton from "@/components/WhatsAppFloatingButton";
import { CartProvider } from "@/context/CartContext";

export const metadata: Metadata = {
  metadataBase: new URL("https://vapestoregurugram.com"),
  title: {
    default: "Vape Store Gurgaon | Buy Vapes Online | 30-60 Min Express Delivery Delhi NCR",
    template: "%s | Vape Store Gurgaon",
  },
  description:
    "Buy 100% authentic disposable vapes, pod kits, coils & imported nic salts in Gurgaon, Delhi & Noida NCR. Superfast 30-60 min express delivery in Gurgaon, same-day delivery in Delhi & Noida. Cash on Delivery (COD) & UPI available. WhatsApp: +91 89509 53934.",
  keywords: [
    // 1. Gurgaon & Gurugram Core Commercial Keywords
    "Vape Store Gurgaon",
    "Vape Store in Gurgaon",
    "Vape Shop Gurgaon",
    "Vape Shop in Gurgaon",
    "Vape Store Gurugram",
    "Vape Store in Gurugram",
    "Vape Shop Gurugram",
    "Vape Shop in Gurugram",
    "Vape Delivery Gurgaon",
    "Vape Delivery in Gurgaon",
    "Vape Delivery Gurugram",
    "Vape Delivery in Gurugram",
    "Buy Vape Online Gurgaon",
    "Buy Vape Online Gurugram",
    "Vape Store Near Me Gurgaon",
    "Vape Shop Near Me Gurgaon",
    "Vape Store Near Me Gurugram",
    "Vape Shop Near Me Gurugram",
    "Vape Store Open Now Gurgaon",
    "Vape Shop Open Now Gurugram",
    "Best Vape Store Gurgaon",
    "Best Vape Shop Gurugram",
    "Authentic Vape Store Gurgaon",
    "Original Vape Shop Gurugram",
    "Online Vape Delivery Gurgaon",
    "Online Vape Delivery Gurugram",
    "Disposable Vapes Gurgaon",
    "Disposable Vapes Gurugram",
    "Pod Systems Gurgaon",
    "Pod Systems Gurugram",
    "Vape Coils Gurgaon",
    "Nicotine Salts Gurgaon",
    "Nic Salts Gurugram",
    "E Liquids Gurgaon",
    "Vape Juice Gurgaon",

    // 2. Gurgaon Micro-Localities & Sector Targeting
    "Vape Store DLF Cyber City",
    "Vape Shop Cyber Hub Gurgaon",
    "Vape Delivery DLF Cyber City",
    "Vape Store Galleria Market DLF",
    "Vape Shop Galleria Market Gurgaon",
    "Vape Delivery DLF Phase 1",
    "Vape Delivery DLF Phase 2",
    "Vape Delivery DLF Phase 3",
    "Vape Delivery DLF Phase 4",
    "Vape Delivery DLF Phase 5",
    "Vape Store DLF Phase 1",
    "Vape Store DLF Phase 2",
    "Vape Store DLF Phase 3",
    "Vape Store DLF Phase 4",
    "Vape Store DLF Phase 5",
    "Vape Delivery Golf Course Road",
    "Vape Store Golf Course Road Gurgaon",
    "Vape Delivery Golf Course Extension Road",
    "Vape Store Golf Course Ext Road",
    "Vape Store Sohna Road Gurgaon",
    "Vape Delivery Sohna Road",
    "Vape Store MG Road Gurgaon",
    "Vape Delivery MG Road",
    "Vape Store Sector 29 Gurgaon",
    "Vape Delivery Sector 29",
    "Vape Store Sector 14 Gurgaon",
    "Vape Store Sector 15 Gurgaon",
    "Vape Store Sector 21 Gurgaon",
    "Vape Store Sector 22 Gurgaon",
    "Vape Store Sector 23 Gurgaon",
    "Vape Store Sector 31 Gurgaon",
    "Vape Store Sector 40 Gurgaon",
    "Vape Store Sector 42 Gurgaon",
    "Vape Store Sector 43 Gurgaon",
    "Vape Store Sector 45 Gurgaon",
    "Vape Store Sector 46 Gurgaon",
    "Vape Store Sector 47 Gurgaon",
    "Vape Store Sector 48 Gurgaon",
    "Vape Store Sector 49 Gurgaon",
    "Vape Store Sector 50 Gurgaon",
    "Vape Store Sector 51 Gurgaon",
    "Vape Store Sector 52 Gurgaon",
    "Vape Store Sector 53 Gurgaon",
    "Vape Store Sector 54 Gurgaon",
    "Vape Store Sector 55 Gurgaon",
    "Vape Store Sector 56 Gurgaon",
    "Vape Store Sector 57 Gurgaon",
    "Vape Store Sector 65 Gurgaon",
    "Vape Store Sector 66 Gurgaon",
    "Vape Store Sector 82 Gurgaon",
    "Vape Store Sector 83 Gurgaon",
    "Vape Store Sector 84 Gurgaon",
    "Vape Delivery Sushant Lok 1",
    "Vape Delivery Sushant Lok 2",
    "Vape Delivery South City 1",
    "Vape Delivery South City 2",
    "Vape Delivery Nirvana Country Gurgaon",
    "Vape Delivery Malibu Towne",
    "Vape Delivery Palam Vihar Gurgaon",
    "Vape Store Ambience Island Gurgaon",
    "Vape Delivery New Gurgaon",

    // 3. Delhi / South Delhi / Central Delhi / NCR Locality Searches
    "Vape Store in Delhi",
    "Vape Shop in Delhi",
    "Vape Delivery Delhi",
    "Vape Delivery in Delhi",
    "Buy Vape Online Delhi",
    "Vape Store Near Me Delhi",
    "South Delhi Vape Store",
    "South Delhi Vape Delivery",
    "Same Day Vape Delivery Delhi",
    "Vape Store Saket",
    "Vape Delivery Saket",
    "Vape Store Hauz Khas",
    "Vape Delivery Hauz Khas",
    "Vape Store Greater Kailash",
    "Vape Store GK 1",
    "Vape Store GK 2",
    "Vape Delivery Greater Kailash",
    "Vape Store Vasant Kunj",
    "Vape Delivery Vasant Kunj",
    "Vape Store Vasant Vihar",
    "Vape Delivery Vasant Vihar",
    "Vape Store Defence Colony",
    "Vape Delivery Defence Colony",
    "Vape Store Green Park",
    "Vape Delivery Green Park",
    "Vape Store South Extension",
    "Vape Delivery South Extension",
    "Vape Store Malviya Nagar",
    "Vape Delivery Malviya Nagar",
    "Vape Store Lajpat Nagar",
    "Vape Delivery Lajpat Nagar",
    "Vape Store Connaught Place CP",
    "Vape Delivery Connaught Place",
    "Vape Store Dwarka",
    "Vape Delivery Dwarka Sector 12",
    "Vape Store Janakpuri",
    "Vape Store Rajouri Garden",
    "Vape Store Punjabi Bagh",
    "Vape Store Rohini",
    "Vape Delivery Rohini",
    "Vape Store Pitampura",
    "Vape Delivery Pitampura",
    "Vape Store Model Town Delhi",
    "Vape Store Civil Lines Delhi",

    // 4. Noida, Greater Noida, Ghaziabad & Faridabad
    "Vape Store in Noida",
    "Vape Shop in Noida",
    "Vape Delivery Noida",
    "Vape Delivery in Noida",
    "Vape Store Sector 18 Noida",
    "Vape Delivery Sector 18 Noida",
    "Vape Store Sector 50 Noida",
    "Vape Store Sector 62 Noida",
    "Vape Delivery Sector 62 Noida",
    "Vape Store Sector 137 Noida",
    "Vape Delivery Noida Expressway",
    "Vape Store Greater Noida",
    "Vape Delivery Greater Noida",
    "Same Day Vape Delivery Noida",
    "Vape Store Indirapuram",
    "Vape Delivery Indirapuram",
    "Vape Store Vaishali Ghaziabad",
    "Vape Store Faridabad",
    "Vape Delivery Faridabad",
    "Vape Store Sector 15 Faridabad",

    // 5. Popular Brands & Specific Product Queries
    "Yuoto Thanos Gurgaon",
    "Yuoto Thanos 5000 Puffs Gurgaon",
    "Yuoto Thanos Price Delhi",
    "Yuoto Thanos Antonovka Apple",
    "Yuoto Digi 15000 Puffs",
    "Yuoto Digi Grape Ice",
    "Elf Bar Gurgaon",
    "Elf Bar Delhi",
    "Elf Bar BC5000 Gurgaon",
    "Elf Bar BC5000 Watermelon Ice",
    "Elf Bar Raya D1 13000 Puffs",
    "Elf Bar Raya D2 20000 Puffs",
    "Elf Bar Raya D2 Watermelon Ice",
    "Elf Bar Raya D3 25000 Puffs",
    "Elf Bar Raya D3 All Flavors",
    "Elfbar GH23000 Blue Razz Ice",
    "Elfbar GH23000 Kiwi Passion Fruit",
    "Elf Bar Ice King 30000 Puffs",
    "Elf Bar Ice King Blue Razz Lemonade",
    "Elfworld 12000 Puffs Mint Menthol",
    "Lost Mary Gurgaon",
    "Lost Mary MT15000 Turbo",
    "Lost Mary 15000 Puffs Buy Online",
    "Lost Mary Delivery Delhi NCR",
    "IGET Vape Gurgaon",
    "IGET Moon 5000 Puffs",
    "IGET Bar 3500 Puffs Delhi",
    "IGET Power B15000 Puffs",
    "IGET Sun KP20000 Puffs",
    "IGET Sun Watermelon Blueberry",
    "Uwell Caliburn Gurgaon",
    "Uwell Caliburn G3 Pod Kit",
    "Uwell Caliburn GK3 Pod System",
    "Uwell Caliburn Tenet Kit",
    "Caliburn Replacement Pods Gurgaon",
    "Arabisk 40K Puffs Disposable Vape",
    "Arabisk Vape Shop Gurgaon",
    "VGod Nic Salt Gurgaon",
    "Dinner Lady Lemon Tart E Liquid",
    "Skwezed Salt E Liquid Delhi",
    "Nasty Juice Nic Salt Delivery",
    "Heets Vanilla Tobacco Gurgaon",
    "IQOS Iluma Terea Sticks Gurgaon",

    // 6. Puff Count Searches
    "5000 Puffs Vape Gurgaon",
    "8000 Puffs Disposable Vape",
    "10000 Puffs Vape Delhi NCR",
    "12000 Puffs Disposable Vape Gurgaon",
    "15000 Puffs Vape Gurgaon",
    "20000 Puffs Disposable Vape",
    "25000 Puffs Vape Gurgaon",
    "30000 Puffs Vape Gurgaon",
    "40000 Puffs Disposable Vape Gurgaon",
    "Highest Puffs Disposable Vape",
    "Big Puff Disposable Vape India",
    "Rechargeable Disposable Vape Gurgaon",

    // 7. Categories, Flavors & Nicotine Strengths
    "Disposable Vapes Delhi NCR",
    "Refillable Pod Kits Gurgaon",
    "Vape Mod Kits Gurgaon",
    "Sub Ohm Vape Kits Delhi",
    "Nicotine Salt E Liquid Gurgaon",
    "20mg Nic Salt Gurgaon",
    "50mg Nic Salt Delhi NCR",
    "Freebase E Juice Gurgaon",
    "0 Nicotine Vape Gurgaon",
    "Mint Menthol Vape Gurgaon",
    "Watermelon Ice Vape Gurgaon",
    "Blueberry Ice Disposable Vape",
    "Mango Ice Disposable Vape",
    "Grape Ice Vape Gurgaon",
    "Strawberry Kiwi Disposable",
    "Double Apple Shisha Vape",
    "Tobacco Vanilla Nic Salt",
    "Vape Replacement Coils Gurgaon",
    "Vape Cartridges Gurgaon",

    // 8. Buyer Intent, Payment & Express Delivery Terms
    "30 Min Vape Delivery Gurgaon",
    "60 Min Vape Delivery Gurgaon",
    "Same Day Vape Delivery Delhi NCR",
    "Express Vape Delivery Gurgaon",
    "Late Night Vape Delivery Gurgaon",
    "24x7 Vape Delivery Gurgaon",
    "24 Hours Vape Delivery Delhi",
    "Midnight Vape Delivery Gurgaon",
    "Cash on Delivery Vape Gurgaon",
    "Vape COD Gurgaon",
    "Vape COD Delhi",
    "Vape Cash on Delivery Delhi NCR",
    "Vape Doorstep UPI Payment",
    "Order Vape on WhatsApp Gurgaon",
    "WhatsApp Vape Order Delhi NCR",
    "Vape Store Contact Number Gurgaon",
    "Discreet Packaging Vape Delivery",
    "100% Authentic Sealed Vape Gurgaon",
    "Scratch Code Verified Vapes",
    "Original Vape Store India",
    "Best Online Vape Store Delhi NCR",
    "Vape Store Gurgaon vapestoregurugram.com",
  ],
  authors: [{ name: "Vape Store Gurgaon" }],
  creator: "Vape Store Gurgaon",
  publisher: "Vape Store Gurgaon",
  metadataBase: new URL("https://vapestoregurugram.com"),
  alternates: {
    canonical: "/",
  },
  other: {
    "geo.region": "IN-HR, IN-DL, IN-UP",
    "geo.placename": "Gurgaon, Gurugram, New Delhi, South Delhi, Noida, Delhi NCR",
    "geo.position": "28.4682;77.0822",
    "ICBM": "28.4682, 77.0822",
  },
  openGraph: {
    title: "Vape Store Gurgaon | Buy Vapes Online | 30-60 Min Express Delivery",
    description:
      "Buy 100% authentic disposable vapes, pod kits & imported nic salts in Gurgaon & Delhi NCR. Superfast 30-60 min express delivery with Cash on Delivery (COD) & UPI.",
    url: "https://vapestoregurugram.com",
    siteName: "Vape Store Gurgaon",
    locale: "en_IN",
    type: "website",
    images: [
      {
        url: "https://vapestoregurugram.com/banners/vapestoregurgaon%20banner.png",
        width: 1953,
        height: 805,
        alt: "Vape Store Gurgaon - Premium Vapes & Pods Delivery",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Vape Store Gurgaon | 30-60 Min Express Delivery",
    description:
      "Order 100% authentic disposable vapes & pod kits in Gurgaon & Delhi NCR. Cash on delivery available.",
    images: ["https://vapestoregurugram.com/banners/vapestoregurgaon%20banner.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/icon.png", type: "image/png" },
      { url: "/favicon.ico" },
    ],
    apple: [
      { url: "/apple-icon.png", type: "image/png" },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const localBusinessSchema = {
    "@context": "https://schema.org",
    "@type": ["Store", "VapeShop"],
    "@id": "https://vapestoregurugram.com/#store",
    name: "Vape Store Gurgaon",
    alternateName: [
      "Vape Store in Gurgaon",
      "Vape Store Gurugram",
      "Vape Store in Gurugram",
      "Vape Shop Gurgaon",
      "Vape Delivery Gurgaon",
      "Vape Delivery Gurugram",
      "Vape Store Delhi NCR",
      "Vape Store Noida",
    ],
    url: "https://vapestoregurugram.com",
    logo: "https://vapestoregurugram.com/icon.png",
    image: "https://vapestoregurugram.com/banners/vapestoregurgaon%20banner.png",
    description:
      "Gurgaon's #1 premier store for 100% authentic disposable vapes, refillable pod kits, coils & imported nic salts. 30-60 min express delivery in Gurgaon (DLF, Cyber City, Golf Course Road) & same-day delivery in Delhi NCR with COD & UPI.",
    telephone: "+91 89509 53934",
    priceRange: "₹₹",
    paymentAccepted: ["Cash on Delivery", "UPI", "Google Pay", "PhonePe", "Paytm"],
    currenciesAccepted: "INR",
    hasMap: "https://maps.google.com/?q=Galleria+Market+DLF+Phase+4+Gurgaon",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Galleria Market, DLF Phase 4",
      addressLocality: "Gurgaon",
      addressRegion: "Haryana",
      postalCode: "122002",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: 28.4682,
      longitude: 77.0822,
    },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
          "Sunday",
        ],
        opens: "10:00",
        closes: "23:30",
      },
    ],
    areaServed: [
      { "@type": "City", name: "Gurgaon" },
      { "@type": "City", name: "Gurugram" },
      { "@type": "AdministrativeArea", name: "DLF Cyber City" },
      { "@type": "AdministrativeArea", name: "DLF Phase 1-5" },
      { "@type": "AdministrativeArea", name: "Golf Course Road" },
      { "@type": "AdministrativeArea", name: "Golf Course Extension" },
      { "@type": "AdministrativeArea", name: "Sohna Road" },
      { "@type": "City", name: "Delhi" },
      { "@type": "City", name: "South Delhi" },
      { "@type": "City", name: "Noida" },
      { "@type": "City", name: "Greater Noida" },
    ],
  };

  const websiteSchema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": "https://vapestoregurugram.com/#website",
    url: "https://vapestoregurugram.com",
    name: "Vape Store Gurgaon",
    description:
      "Premier Vape Store in Gurgaon & Delhi NCR - 30-60 min express delivery with Cash on Delivery & UPI.",
    publisher: {
      "@id": "https://vapestoregurugram.com/#store",
    },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: "https://vapestoregurugram.com/search?q={search_term_string}",
      },
      "query-input": "required name=search_term_string",
    },
  };

  return (
    <html lang="en" className="h-full bg-slate-50">
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900 antialiased selection:bg-purple-100 selection:text-purple-700">
        {/* Global Structured Data JSON-LD for Google Local SEO & Sitelinks Searchbox */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
        <CartProvider>
          <Navbar />
          <div className="flex-1">{children}</div>
          <Footer />
          <CartDrawer />
          <WhatsAppFloatingButton />
        </CartProvider>
      </body>
    </html>
  );
}
